### PR TITLE
The black box

### PR DESCRIPTION
**Pull request by kurisam**
# Description

Added new blog article "The Black Box", Chem-E-Car's Junior team's car. It details the features of the car and how it is made

Fixes # (issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Update old infomation
- [X] New blog post or news article
- [ ] New member

# Checklist:
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] The webmaster as reviewed my code and approved it to be merged

### CODE REVIEW

**Comment by jd4900** [comment]
Some changes need to be made to the equations and the formatting as they are hard to read.

**Comment by csianglim** [comment]
Use LaTeX and render with Mathjax for the equations, see how it's done in www.ubcenvision.com/blog/2017/02/28/fuelcell.html @kurisam @jd4900

**Comment by kurisam** [comment]
I've reformatted it using Latex in "The Black Box" branch but I can't see if the changes have worked. Since it doesn't seem to reflect changes for this syntax in preview mode. Is there a work around so i can test how the equations now look without pulling the branch and checking the website? @csianglim @jd4900

**Comment by csianglim** [comment]
Paste your equations into an online viewer to check:
http://saxarona.github.io/mathjax-viewer/

When you have time, meet with @jd4900, he can help you set up your computer
to develop locally. @kurisam

**Pull request merged**
