### PR TITLE
changed the link for mathjax to fix rendering

### PR DESCRIPTION
**Pull request by kurisam**
# Description

Updated the link that includes mathjax to fix mathjax rendering problems

Fixes # 302

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Update old infomation
- [ ] New blog post or news article
- [ ] New member

# Checklist:
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] The webmaster as reviewed my code and approved it to be merged

### CODE REVIEW

**Comment by csianglim** [comment]
@kurisam have u tried this locally to see if it works?

**Comment by kurisam** [comment]
tested locally and it worked

**Comment by csianglim** [comment]
Closes issue #302

**Comment by jd4900** [comment]
Good work on this @kurisam !

**Pull request merged**
